Lang.prototype.pack.zh = {
	"token": {
        "Bohol South Beach Hotel" : "本他奥 奥本他 奥本他学会利",
        "Welcome" : "奥奥奥",
        "About Us" : "奥会暂最",
        "Location" :  "护朝鲜极端",
		"Getting Here" : "原本他曾在乔",
		"Contact Us" : "考虑发的",
		"Accomodations" : "朝发动预",
		"ServicesAndAmenities" : "了获们学会利用自己",
		"Contact Us" : "及他公民撤离韩国",
		"Destinations" : "承诺因为他自己",
		"Gallery" : "上海市家星",
		"Room Reservations" : "钱的开始追求长生",
		"HotelStreetAddress" : "钱的开始,追求长生,在判决书中说, 焕晶是否会",

		"Bohol South Beach Hotel About Us" : "钱的开始追求长生",
		"AboutUs0" : "0钱的的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求",
		"AboutUs1" : "1钱的的开始追求长钱的长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长生生生生钱的开始追求长钱的开始追求长钱的开始追求长钱的开始追求长生",
		"AboutUs2" : "2钱的开始追求钱的开始追求长长生",
		"AboutUs3" : "3政府表示近年来减少了死刑的使用，但中国并不公布有关统计数字，人们仍认为中国被执行死刑的犯人数量远高于世界上其他任何国家。批评中国法律制度的人认为，政府",
		"AboutUs4" : "4钱的开政府表示近年来减少了死刑的使用，但中国并不公布有关统计数字，人们仍认为中国被执行死刑的犯人数量远高于世界上其他任何国家。批评中国法律制度的人认为，政府政府表示近年来减少了死刑的使用，但中国并不公布有关统计数字，人们仍认为中国被执行死刑的犯人数量远高于世界上其他任何国家。批评中国法律制度的人认为，政府",
		"AboutUs5" : "5钱的开始求目前尚不清楚莫焕晶是否会对判决提出上诉，北京的最高人民法院必须对死刑判决进行核准。",
		"AboutUs6" : "6莫焕晶在受审期间公开的一封信里曾表示懊悔，她说，“如果判我死刑能使一切从头再来，我也愿意接受死刑。",
		"AboutUs7" : "7钱的开莫焕晶在受审期间公开的一封信里曾表示懊悔，她说，“如果判我死刑能使一切从头再来，我也愿意接受死刑。",
		"AboutUs8" : "8钱的开始追求钱的开始追求长长求钱的开始追求长长生生",
		"AboutUs9" : "9正义不只是判处被告死刑，”党琳山对中国著名新闻杂志《财新》说",
		"AboutUs10" : "10钱的开始追求钱求长长生的开始追求长长生",
		"AboutUs11" : "11法院在判决书中说，莫焕晶在犯罪前曾上网查找放火方法，还查询了“放火要坐牢吗？”等问题。法官说，她为了偿还债务，从林家偷走了价值18万元（约合2.8万美元）的财产，包括珠宝和手表，还向林家借了11.4万元（约合1.8万美）",
		"AboutUs12" : "12钱的开始追求钱的开始追求长长生求长长生",
		"AboutUs13" : "13目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。",
		"AboutUs14" : "14钱的开始追求钱钱的开始追求长长生的开始追求目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。长长生",
		"AboutUs15" : "15钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Balicasag Island" : "钱的开政府表示近年来减少了",
		"Balicasag Island" : "开政府表示近年来",
		"Virgin Island" : "开政府表示",
		"Danao Beach" : "开政府表示近",
		"Chocolate Hills" : "期间公开 追求钱",
		"Tarsiers" : "开间公开",
		"Language" : "追求钱",
		"BI1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"BI2" : "2钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Chocolate Hills" : "钱的开政府表示近年来减少了",
		"CH1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"CH2" : "2钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		
		"Bohol South Beach Hotel Contact Us" : "钱的开政府表示近年来减少了",
		"Bohol South Beach Hotel can be contacted in a number of ways" : "的法律人民法院必须对死刑判决进行核准",
		"Email" : "尚不清楚莫焕",
		"Social Media" : "清楚莫焕",
		"Our email address is" : "清楚莫焕",
		"Telephone" : "尚不清楚莫焕",
		"Our telephone number is +63 917 315 2698" : "清楚莫焕",
		"We are active on" : "不清楚莫焕晶是否会对判决提出上诉",

		"Bohol South Beach Hotel Danao Beach" : "钱的开政府表示近年来减少了",
		"DB1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Destinations" : "钱的开政府表示近年来减少了",
		"Destinations" : "钱开近年来减少了",
		"D1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Dining" : "钱的近年来减少了",
        "Infinity Pool" : "开政府表示",
        "Rooftop Deck" : "开政府表示近",
        "Dining" : "期间公开 追求钱",
        "Ultra Lounge" : "开间公开",
		"Dining Facilities" : "钱开近年来减少了",
		"Dining1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel First Floor Deluxe Room" : "钱的近年来减少近年来减少了了近年来减少了",
        "First Floor Deluxe" : "期间公开 追求钱",
        "First Floor Deluxe Room" : "期间公开 追求钱",
        "Second Floor Deluxe" : "开间公开",
		"Second Floor Deluxe Suite" : "钱开近年来减少了",
		"FFD1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Image Gallery" : "钱的近年来减少近年来减少了了近年来减少了",

		"Bohol South Beach Hotel Getting Here" : "钱的近来减少了了近年来减少了",
		"Getting To Bohol" : "钱开近年来减少了",
		"GH1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH2" : "2钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH3" : "3钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH4" : "4钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH5" : "5钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH6" : "6钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH7" : "7钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH8" : "8钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH9" : "9钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH10" : "10钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"GH11" : "11钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",
		"By Airplane" : "钱 开近年来减少了",
		"By Ferry" : "钱开近 年来减少了",
		"Hotel Shuttle" : "钱开近年来减少了",

		"Bohol South Beach Hotel Location" : "钱的近来减少了了近年来减少了",
		"L1" : "11钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Infinity Pool" : "钱的近来减少了了近年来减少了",
		"IP1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Ultra Lounge" : "钱的近来减少了了近年来减少了",
		"UL1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Rooftop" : "钱的近来减少了了近年来减少了",
		"R1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Room Accomodations" : "钱的近来减少了了近年来减少了",
		"Rooms1" : "1钱的近来减少了了近年来减少了",

		"ServiesAndAmenities2" : "钱的近来减少了了近年来减少了",
		"SAA1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Tarsier Sanctuary" : "钱的近来减少了了近年来减少了",
		"Tarsier Sanctuary" : "钱的近来 减少了了近年 来减少了",
		"T1" : "1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Virgin Island" : "钱的近来减少了了近年来减少了",
		"VI1" : "1钱的近来减少了了近年来减少了",
		"VI2" : "2钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Second Floor Deluxe Suite" : "SFDS0钱的近来减少了了近年来减少了",
		"SFDS1" : "SFDS1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

		"Bohol South Beach Hotel Second Floor Deluxe Room" : "SFDR99钱 的近来减少了 了近年来减少了",
		"Second Floor Deluxe Room" : "SFDR0钱 的近来减少了 了近年来减少了",
		"SFDR1" : "SFDR1钱的开始追求钱的开目前尚不清楚莫焕晶是否会对判决提出上诉。根据中国的法律，北京的最高人民法院必须对死刑判决进行核准。始追求长长生钱的开始追求长长生",

	},
},
Lang.prototype.pack.de = {
	"token": {
        "Bohol South Beach Hotel" : "Bohol South Beach Hotel",
        "Welcome" : "Wilkommen",
        "About Us" : "Über uns",
        "Location" :  "Hotel Adresse",
		"Getting Here" : "Hotel Anreise",
		"Contact Us" : "Hotel Kontakt",
		"Accomodations" : "Hotel Zimmer",
		"ServicesAndAmenities" : "Ausstattung",
		"Contact Us" : "Kontakt",
		"Destinations" : "Ausflugsorte",
		"Gallery" : "Galerie",
		"Room Reservations" : "Room Reservations",
		"HotelStreetAddress" : "Bohol South Beach Hotel, Danao Beach, Panglao, Bohol, Philippinen.",
		"Bohol South Beach Hotel About Us" : "Über uns",
		"AboutUs0" : "Das Bohol South Beach Hotel wurde im Sommer 2012 erbaut und ergänzt die tropische Insel Atmosphäre mit dem Flair von Miami South Beach.",
		"AboutUs1" : "Das dreistöckige Gebäude ist nach höchsten Standards designt und ausgestattet. Moderner Style in tropischem Umfeld - der perfekte Ort für Ihren Urlaub.",
		"AboutUs2" : "Unser Hotel bietet",
		"AboutUs3" : "Alle Zimmer sind mit privatem und modernen Bad ausgestattet",
		"AboutUs4" : "Durchgängig besetzte Rezeption",
		"AboutUs5" : "Zimmerservice von 6:00 bis 23:00",
		"AboutUs6" : "Tägliche Zimmerreinigung",
		"AboutUs7" : "Wäscheservice",
		"AboutUs8" : "Regelmäßiger, gratis Shuttle zu den Attraktivitäten von Alona Beach",
		"AboutUs9" : "Sicherheitsdienst",
		"AboutUs10" : "Kein Mindestaufenthalt erforderlich",
		"AboutUs11" : "Das Wetter ist das ganze Jahr über fantastisch! Unsere Gäste können im warmen Pazifik schwimmen oder sich an unserem Infinity Pool entspannen.",
		"AboutUs12" : "Unsere Dachterrasse ist der geeignete Ort, den Trubel von Danao Beach zu beobachten, den Sonnenaufgang zu erleben oder den Abend mit dem Sonnenuntergang zu beginnen.",
		"AboutUs13" : "Verbringen Sie die Abende ganz nach Ihrem Geschmack: Unweit vom Hotel, am Panglao Strip in Alona Beach, finden Sie zahlreiche Restaurants und Clubs. Oder ziehen Sie sich einfach zurück in die Ruhe des Bohol South Beach Hotels.",
		"AboutUs14" : "In nur wenigen Minuten können Sie vom Hotel aus per Boot zu weltbekannten Tauchorten gelangen. Unser Hotel Concierge hilft Ihnen gerne beim Buchen.",
		"AboutUs15" : "Gerne holen wir Sie bei Ihrer Ankunft ab - egal, ob Sie per Flugzeug, Fähre oder Pumpboat anreisen.",

		"Bohol South Beach Hotel Balicasag Island" : "Insel Balicasag",
		"Balicasag Island" : "Insel Balicasag",
		"Virgin Island" : "Insel Virgin",
		"Danao Beach" : "Danao Beach",
		"Chocolate Hills" : "Chocolate Hills",
		"Tarsiers" : "Tarsiere",
		"Language" : "Sprache",
		"BI1" : "Unweit von Panglao liegt die kleine, attraktive Insel namens Balicasag, die von vielen Urlaubern besucht wird. Balicasag bietet eine der besten und ergiebigsten Tauchgründe in den Visayas, und große Strandbereiche um diese Insel herum eignen sich bestens zum Schnorcheln.",
		"BI2" : "Die Fahrt nach Balicasag dauert etwa 20 Minuten im Pumpboat, welches Sie direkt am Hotelstrand abholt. Gerne organisieren wir den Ausflug für Sie",

		"Bohol South Beach Hotel Chocolate Hills" : "Bohol South Beach Hotel Chocolate Hills",
		"CH1" : "Die Chocolate Hills gehören zu den wichtigsten und bedeutendsten Sehenswürdigkeiten der Philippinen. 1.250 Hügel - manche Geologen sprechen sogar von mehr als 1.700 - sind über ein Gebiet von circa 50 Quadratkilometern verteilt. Während der Regenzeit sind die Hügel mit verschiedensten Gräsern, Farnen und Zuckerrohrarten bewachsen, die sich in den heißen Sommermonaten braun färben - daher der Name Chocolate Hills.",
		"CH2" : "Die Chocolate Hills sind auf der Flagge von Bohol abgebildet und symbolisieren den Überfluss der Naturwunder in dieser Provinz. Die Philippine Tourism Authority listet die Chocolate Hills als eine der wichtigsten Touristenattraktionen der Philippen. Sie sind als National Geological Monument registriert und nominiert für die UNESCO World Heritage List.",
		
		"Bohol South Beach Hotel Contact Us" : "Kontakt",
		"Bohol South Beach Hotel can be contacted in a number of ways" : "Wir sind für Sie erreichbar",
		"Email" : "Email",
		"Social Media" : "Soziale Netzwerke",
		"Our email address is" : "Unsere Emailadresse ist",
		"Telephone" : "Telefon",
		"Our telephone number is +63 917 315 2698" : "Unsere Telefonnummer ist +63 917 315 2698",
		"We are active on" : "Sie finden uns auf:",

		"Bohol South Beach Hotel Danao Beach" : "Bohol South Beach Hotel Danao Beach",
		"DB1" : "Danao ist nicht so bekannt und entwickelt wie das nahegelegene Alona Beach. Unser Strand ist aber genauso weiß, und der Pazifik vor unserem Hotel wird von den selben warmen Strömungen umspült.",

		"Bohol South Beach Hotel Destinations" : "Ausflugsorte",
		"Destinations" : "Ausflugsorte",
		"D1" : "Es gibt zahlreiche Sehenswürdigkeiten in der Nähe des Hotels, seien es weltbekannte Tauchorte wie Balicasag - welchen Sie von der Dachterrasse aus sehen können - und Virgin Island, oder die spektakulären Chocolate Hills auf Bohol.",

		"Bohol South Beach Hotel Dining" : "Restaurant",
        "Infinity Pool" : "Infinity-pool",
        "Rooftop Deck" : "Dachterrasse",
        "Dining" : "Restaurant",
        "Ultra Lounge" : "Ultra Lounge",
		"Dining Facilities" : "Restaurant",
		"Dining1" : "Unser Hotel bietet Frühstück, Mittag- und Abendessen. Unser Restaurant befindet sich im 2. Obergeschoss und auf der Dachterrasse. Gerne bringen wir Ihre Mahlzeiten auch auf Ihr Zimmer. Unsere Karte umfasst traditionelle Speisen der Philippinischen Küche, sowie eine Auswahl an westlichen Spezialitäten.",

		"Bohol South Beach Hotel First Floor Deluxe Room" : "Bohol South Beach Hotel Erdgeschoss Deluxe Zimmer",
        "First Floor Deluxe" : "Erdgeschoss Deluxe Zimmer",
        "First Floor Deluxe Room" : "Erdgeschoss Deluxe Zimmer",
        "Second Floor Deluxe" : "Zweites Stockwerk Deluxe Zimmer",
		"Second Floor Deluxe Suite" : "Zweites Stockwerk Deluxe Suite",
		"FFD1" : "Unsere Deluxe Zimmer (Erdgeschoss) verwöhnen Sie mit einem traumhaften Blick auf das Meer. Ihre Veranda grenzt direkt an unseren Infinity Pool.",

		"Bohol South Beach Hotel Image Gallery" : "Foto Galerie",

		"Bohol South Beach Hotel Getting Here" : "Anreise",
		"Getting To Bohol" : "Anreise",
		"GH1" : "Das wunderschöne Bohol gehört zu der Central Visaysa Inselkette und liegt im geographischen Zentrum der Philippinen.",
		"GH2" : " ",
		"GH3" : "Internationale Flughäfen befinden sich in Manila und Cebu. Anreise über Manila Es empfiehlt sich, von Manila einen inländischen Anschlussflug nach Tagbilaran zu nehmen (Flugzeit etwa eine Stunde, tägliche Flüge). Alternativ können Sie einen Weiterflug nach Cebu buchen oder die gesamte Strecke von Manila bis nach Bohol mit der Fähre zurücklegen (etwa 25 Stunden).",
		"GH4" : "Das nähergelegene Cebu wird von Silk Air, Malaysia Airlines und Cathy Pacific über Singapur, Kuala Lumpur und Hong Kong angeflogen. Diese Routen ersparen es Ihnen, in Manila vom internationalen zum inländischen Flughafen transferieren zu müssen. Die Reise von Cebu nach Bohol muss mit einer Fähre zurückgelegt werden - egal, ob Sie Cebu international oder von Manila aus anreisen. Der Hafen in Cebu ist etwa 30 Minuten vom Flughafen entfernt.",
		"GH5" : " ",
		"GH6" : "Zwischen Cebu und Tagbilaran verkehren regelmäßig Fähren. Im Schnellboot dauert die Reise etwa 1 1/2 Stunden, für die normale Fähre müssen Sie gut 4 Stunden einkalkulieren.",
		"GH7" : "Die günstigste Verbindung zwischen Cebu und Tagbilaran ist es, mit der Fähre nach Tubigon zu reisen und von dort mit dem Bus nach Tagbilaran. Je nach Verbindung kann dieses auch die schnellste Verbindung nach Tagbilaran sein.",
		"GH8" : "Der hoteleigene Shuttleservice besteht aus",
		"GH9" : "ein klimatisierter 7-Personen-Minivan",
		"GH10" : "ein klimatisierter 15-Personen-Minivan",
		"GH11" : "Beide Fahrzeuge können Hotelgäste sowohl am Eingangshafen als auch an einem der lokalen Zielorte abholen und abgeben",
		"By Airplane" : "Mit Flugzeug",
		"By Ferry" : "Mit Fähre von Cebu",
		"Hotel Shuttle" : "Hotel Shuttle",

		"Bohol South Beach Hotel Location" : "Adresse",
		"L1" : "Unser Hotel liegt direkt am Danao Beach, an der südlichen Küste von Panglao. Die Fahrt zum Tagbilaran Airport auf Bohol dauert etwa 25 Minuten.",

		"Bohol South Beach Hotel Infinity Pool" : "Infinity-pool",
		"IP1" : "Unser Infinity Pool ist 4 Meter breit, 12 Meter lang und zwischen 1 und 2 Meter tief. Trivia: Der Pool ist ein Nachbau von dem Pool, den der Fußballstar Cristiano Ronaldo von Real Madrid bei sich zu Hause hat!",

		"Bohol South Beach Hotel Ultra Lounge" : "Ultra Lounge",
		"UL1" : "Entspannen Sie mit einem tropischen Getränk und Beats in unserer Ultra Lounge.",

		"Bohol South Beach Hotel Rooftop" : "Dachterrasse",
		"R1" : "Von der Dachterrasse aus können Sie das Meer bis zum Horizont sehen und das rege maritime Treiben beobachten - seien es die Pumpboats der lokalen Fischer und Händler oder der Schiffsverkehr der Inselkette. Genießen Sie den Blick auf den Strand, umgeben von einem lauen Wind und dem Rascheln der Kokospalmen.",

		"Bohol South Beach Hotel Room Accomodations" : "Zimmer",
		"Rooms1" : "Unser Hotel hat seben unterschiedliche Zimmerkategorien",
		"Rooms2" : "Erdgeschoss Deluxe Zimmer",
		"Rooms3" : "Zweites Stockwerk Deluxe Zimmer",
		"Rooms4" : "Familiensuite im zweiten Stock",
		"Rooms5" : "Oberer Gartenblick im dritten Stock Deluxe",
		"Rooms6" : "Deluxe Zimmer mit Gartenblick in der oberen Etage",
		"Rooms7" : "Business-Zimmer mit Queensize-Bett",
		"Rooms8" : "Budget Zimmer mit zwei Einzelbetten",

		"First Floor Ocean View Deluxe" : "Erdgeschoss mit Meerblick",
		"Second Floor Ocean View Deluxe" : "Zweiter Stock mit Meerblick",
		"Second Floor Family Suite" : "Familiensuite im zweiten Stock",

		"ServiesAndAmenities2" : "Ausstattung",
		"SAA1" : "Das Bohol South Beach Hotel macht Ihnen den Aufenthalt mit Ausstattungen wie dem Infinity Pool, der Dachterrasse, dem Restaurant und der Tiki Bar am Pool angenehm. Wir haben drei Bars: am Pool, im Restaurant und auf der Dachterrasse. Gerne serviert unser Restaurant Speisen auf Ihr Zimmer. Wir haben Fahrräder, die sie gerne gratis nutzen können. Unsere Motorräder verleihen wir für eine geringe Gebühr.",

		"Bohol South Beach Hotel Tarsier Sanctuary" : "Tarsier-Schongebiet",
		"Tarsier Sanctuary" : "Tarsier-Schongebiet",
		"T1" : "Koboldmakis („Tarsiere“) sind die kleinsten Primaten auf der Welt. Sie leben ausschließlich in den Philippinen und stehen seit 1991 auf der Liste der geschützten Tierarten der Philippinen. Die „Philippine Tarsier Foundation“ ist eine gute Adresse, diese kleinen Primaten zu sehen; die Fahrt im Auto dauert etwa 45 Minuten vom Hotel, und gerne organisieren wir Ihren Ausflug.",

		"Bohol South Beach Hotel Virgin Island" : "Insel Virgin",
		"VI1" : "Insel Virgin (Insel Pungtud)",
		"VI2" : "Nicht vom selben Ruhm wie Balicasag, Pungtud - oder Virgin Island - ist als Tauchgrund ebenfalls spektakulär.",

		"Bohol South Beach Hotel Second Floor Deluxe Suite" : "Zweites Stockwerk Deluxe Suite",
		"SFDS1" : "Von unseren Deluxe Suites im ersten Obergeschoss aus haben Sie einen Panoramablick auf das Meer und den Strand.",

		"Bohol South Beach Hotel Second Floor Deluxe Room" : "Zweites Stockwerk Deluxe Zimmer",
		"Second Floor Deluxe Room" : "Zweites Stockwerk Deluxe Zimmer",
		"SFDR1" : "Von unseren Deluxe Zimmer im ersten Obergeschoss aus haben Sie einen Panoramablick auf das Meer und den Strand.",
	},
};
